[package]
name = "sudoku-generator"
version = "0.1.0"
authors = ["Vasco Fernandes <vasco.box@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
rayon = "1.3.0"
clap = "2.33.1"
rand = "0.7.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "solve"
harness = false